### ISSUE TITLE
Attribute `affinity` was deprecated in version 1.2 of sklearn and was removed in 1.4. Use `metric` instead

### ISSUE THREAD

**Issue by auranic** [ncaptier/Stabilized_ICA#3]
fit() does not compute the decomposition with an error because the attribute `affinity` was deprecated in version 1.2 of sklearn and was removed in 1.4. Use `metric` instead

**Comment by ncaptier** [comment]
Sorry for the delay. I will update the AgglomerativeClustering function to fix the problem.
